export const SCHEDULE = [
  { id:'fajr',    time:'05:00', h:5,  m:0,  task:'Fajr Prayer',               sub:'Begin the day with salah — sets the tone',        cat:'prayer', color:'green',  timeable:false },
  { id:'lc',      time:'06:00', h:6,  m:0,  task:'DSA / Leetcode Session',    sub:'1 problem minimum — arrays, trees, graphs, DP',   cat:'dsa',    color:'blue',   timeable:true  },
  { id:'dhuhr',   time:'12:30', h:12, m:30, task:'Dhuhr Prayer',              sub:'Midday salah — step away from the screen',        cat:'prayer', color:'green',  timeable:false },
  { id:'sql',     time:'13:00', h:13, m:0,  task:'SQL & Databases',           sub:'Joins, indexing, transactions, normalization',    cat:'db',     color:'amber',  timeable:true  },
  { id:'cn',      time:'14:00', h:14, m:0,  task:'Computer Networks',         sub:'TCP/IP, DNS, HTTP, OSI model basics',             cat:'cn',     color:'red',    timeable:true  },
  { id:'asr',     time:'15:30', h:15, m:30, task:'Asr Prayer',                sub:'Afternoon salah',                                 cat:'prayer', color:'green',  timeable:false },
  { id:'spring',  time:'16:00', h:16, m:0,  task:'Spring Boot + AI Project',  sub:'Build REST APIs and integrate AI features',       cat:'spring', color:'purple', timeable:true  },
  { id:'react',   time:'17:30', h:17, m:30, task:'React Polish',              sub:'Hooks, state management, component patterns',     cat:'react',  color:'teal',   timeable:true  },
  { id:'maghrib', time:'18:30', h:18, m:30, task:'Maghrib Prayer',            sub:'Sunset salah — pause everything',                 cat:'prayer', color:'green',  timeable:false },
  { id:'quran',   time:'19:00', h:19, m:0,  task:'Quran Recitation',          sub:'Daily wird — consistency over quantity',          cat:'quran',  color:'pink',   timeable:false },
  { id:'isha',    time:'20:30', h:20, m:30, task:'Isha Prayer',               sub:'Night salah — close the day right',               cat:'prayer', color:'green',  timeable:false },
]

export const PRAYERS = [
  { id:'fajr',    name:'Fajr',    time:'05:00' },
  { id:'dhuhr',   name:'Dhuhr',   time:'12:30' },
  { id:'asr',     name:'Asr',     time:'15:30' },
  { id:'maghrib', name:'Maghrib', time:'18:30' },
  { id:'isha',    name:'Isha',    time:'20:30' },
]

export const QUOTES = [
  { text: '"Verily, with hardship comes ease."',                                             src: '— Quran 94:5' },
  { text: '"And He found you lost and guided you."',                                         src: '— Quran 93:7' },
  { text: '"Take benefit of five before five: youth, health, wealth, free time, life."',    src: '— Prophet ﷺ' },
  { text: '"The strong man is not the one who is physically powerful, but the one who controls himself in anger."', src: '— Prophet ﷺ' },
  { text: '"Be in this world as if you were a stranger or a traveller."',                    src: '— Prophet ﷺ' },
  { text: '"Whoever treads a path seeking knowledge, Allah eases his path to Jannah."',     src: '— Prophet ﷺ' },
  { text: '"Indeed, Allah will not change the condition of a people until they change what is in themselves."', src: '— Quran 13:11' },
  { text: '"So be patient. Indeed, the promise of Allah is truth."',                         src: '— Quran 30:60' },
  { text: '"And whoever relies upon Allah — then He is sufficient for him."',                src: '— Quran 65:3' },
  { text: '"Allah does not burden a soul beyond that it can bear."',                         src: '— Quran 2:286' },
  { text: '"And seek help through patience and prayer."',                                    src: '— Quran 2:45' },
  { text: '"Do not lose hope, nor be sad."',                                                 src: '— Quran 3:139' },
  { text: '"My success is not but through Allah. Upon Him I have relied."',                  src: '— Quran 11:88' },
  { text: '"And remember your Lord when you forget."',                                       src: '— Quran 18:24' },
  { text: '"Indeed, Allah is with those who are patient."',                                  src: '— Quran 2:153' },
  { text: '"Whoever works righteousness — it is for his own soul."',                         src: '— Quran 41:46' },
  { text: '"Nothing will befall us except what Allah has decreed for us."',                  src: '— Quran 9:51' },
  { text: '"The best among you are those who learn the Quran and teach it."',               src: '— Prophet ﷺ' },
  { text: '"A moment of patience in a moment of anger saves a thousand moments of regret."', src: '— Prophet ﷺ' },
  { text: '"Richness is not having many possessions. Rather, true richness is the richness of the soul."', src: '— Prophet ﷺ' },
]

export const MOTIVATIONAL_BANNERS = [
  { text: 'Your consistency today builds the engineer of tomorrow.', icon: '⚡' },
  { text: 'One problem a day keeps the interview anxiety away.', icon: '🧠' },
  { text: 'Allah sees your effort even when no one else does.', icon: '🌙' },
  { text: 'FAST NUCES → Big Tech. You\'re on the path. Stay on it.', icon: '🚀' },
  { text: 'The best time to solve a leetcode problem was yesterday. The second best is now.', icon: '💻' },
  { text: 'Your dua + your grind = unstoppable.', icon: '✨' },
]

export const NEETCODE_150 = [
  // Arrays & Hashing (9)
  { id:1,   title:'Contains Duplicate',                                    slug:'contains-duplicate',                                    topic:'Arrays & Hashing',        difficulty:'Easy'   },
  { id:2,   title:'Valid Anagram',                                         slug:'valid-anagram',                                         topic:'Arrays & Hashing',        difficulty:'Easy'   },
  { id:3,   title:'Two Sum',                                               slug:'two-sum',                                               topic:'Arrays & Hashing',        difficulty:'Easy'   },
  { id:4,   title:'Group Anagrams',                                        slug:'group-anagrams',                                        topic:'Arrays & Hashing',        difficulty:'Medium' },
  { id:5,   title:'Top K Frequent Elements',                               slug:'top-k-frequent-elements',                               topic:'Arrays & Hashing',        difficulty:'Medium' },
  { id:6,   title:'Encode and Decode Strings',                             slug:'encode-and-decode-strings',                             topic:'Arrays & Hashing',        difficulty:'Medium' },
  { id:7,   title:'Product of Array Except Self',                          slug:'product-of-array-except-self',                          topic:'Arrays & Hashing',        difficulty:'Medium' },
  { id:8,   title:'Valid Sudoku',                                          slug:'valid-sudoku',                                          topic:'Arrays & Hashing',        difficulty:'Medium' },
  { id:9,   title:'Longest Consecutive Sequence',                          slug:'longest-consecutive-sequence',                          topic:'Arrays & Hashing',        difficulty:'Hard'   },
  // Two Pointers (5)
  { id:10,  title:'Valid Palindrome',                                      slug:'valid-palindrome',                                      topic:'Two Pointers',            difficulty:'Easy'   },
  { id:11,  title:'Two Sum II',                                            slug:'two-sum-ii-input-array-is-sorted',                      topic:'Two Pointers',            difficulty:'Medium' },
  { id:12,  title:'3Sum',                                                  slug:'3sum',                                                  topic:'Two Pointers',            difficulty:'Medium' },
  { id:13,  title:'Container With Most Water',                             slug:'container-with-most-water',                             topic:'Two Pointers',            difficulty:'Medium' },
  { id:14,  title:'Trapping Rain Water',                                   slug:'trapping-rain-water',                                   topic:'Two Pointers',            difficulty:'Hard'   },
  // Sliding Window (6)
  { id:15,  title:'Best Time to Buy and Sell Stock',                       slug:'best-time-to-buy-and-sell-stock',                       topic:'Sliding Window',          difficulty:'Easy'   },
  { id:16,  title:'Longest Substring Without Repeating Characters',        slug:'longest-substring-without-repeating-characters',        topic:'Sliding Window',          difficulty:'Medium' },
  { id:17,  title:'Longest Repeating Character Replacement',               slug:'longest-repeating-character-replacement',               topic:'Sliding Window',          difficulty:'Medium' },
  { id:18,  title:'Permutation in String',                                 slug:'permutation-in-string',                                 topic:'Sliding Window',          difficulty:'Medium' },
  { id:19,  title:'Minimum Window Substring',                              slug:'minimum-window-substring',                              topic:'Sliding Window',          difficulty:'Hard'   },
  { id:20,  title:'Sliding Window Maximum',                                slug:'sliding-window-maximum',                                topic:'Sliding Window',          difficulty:'Hard'   },
  // Stack (7)
  { id:21,  title:'Valid Parentheses',                                     slug:'valid-parentheses',                                     topic:'Stack',                   difficulty:'Easy'   },
  { id:22,  title:'Min Stack',                                             slug:'min-stack',                                             topic:'Stack',                   difficulty:'Medium' },
  { id:23,  title:'Evaluate Reverse Polish Notation',                      slug:'evaluate-reverse-polish-notation',                      topic:'Stack',                   difficulty:'Medium' },
  { id:24,  title:'Generate Parentheses',                                  slug:'generate-parentheses',                                  topic:'Stack',                   difficulty:'Medium' },
  { id:25,  title:'Daily Temperatures',                                    slug:'daily-temperatures',                                    topic:'Stack',                   difficulty:'Medium' },
  { id:26,  title:'Car Fleet',                                             slug:'car-fleet',                                             topic:'Stack',                   difficulty:'Medium' },
  { id:27,  title:'Largest Rectangle in Histogram',                        slug:'largest-rectangle-in-histogram',                        topic:'Stack',                   difficulty:'Hard'   },
  // Binary Search (7)
  { id:28,  title:'Binary Search',                                         slug:'binary-search',                                         topic:'Binary Search',           difficulty:'Easy'   },
  { id:29,  title:'Search a 2D Matrix',                                    slug:'search-a-2d-matrix',                                    topic:'Binary Search',           difficulty:'Medium' },
  { id:30,  title:'Koko Eating Bananas',                                   slug:'koko-eating-bananas',                                   topic:'Binary Search',           difficulty:'Medium' },
  { id:31,  title:'Find Minimum in Rotated Sorted Array',                  slug:'find-minimum-in-rotated-sorted-array',                  topic:'Binary Search',           difficulty:'Medium' },
  { id:32,  title:'Search in Rotated Sorted Array',                        slug:'search-in-rotated-sorted-array',                        topic:'Binary Search',           difficulty:'Medium' },
  { id:33,  title:'Time Based Key-Value Store',                            slug:'time-based-key-value-store',                            topic:'Binary Search',           difficulty:'Medium' },
  { id:34,  title:'Median of Two Sorted Arrays',                           slug:'median-of-two-sorted-arrays',                           topic:'Binary Search',           difficulty:'Hard'   },
  // Linked List (11)
  { id:35,  title:'Reverse Linked List',                                   slug:'reverse-linked-list',                                   topic:'Linked List',             difficulty:'Easy'   },
  { id:36,  title:'Merge Two Sorted Lists',                                slug:'merge-two-sorted-lists',                                topic:'Linked List',             difficulty:'Easy'   },
  { id:37,  title:'Reorder List',                                          slug:'reorder-list',                                          topic:'Linked List',             difficulty:'Medium' },
  { id:38,  title:'Remove Nth Node From End of List',                      slug:'remove-nth-node-from-end-of-list',                      topic:'Linked List',             difficulty:'Medium' },
  { id:39,  title:'Copy List with Random Pointer',                         slug:'copy-list-with-random-pointer',                         topic:'Linked List',             difficulty:'Medium' },
  { id:40,  title:'Add Two Numbers',                                       slug:'add-two-numbers',                                       topic:'Linked List',             difficulty:'Medium' },
  { id:41,  title:'Linked List Cycle',                                     slug:'linked-list-cycle',                                     topic:'Linked List',             difficulty:'Easy'   },
  { id:42,  title:'Find the Duplicate Number',                             slug:'find-the-duplicate-number',                             topic:'Linked List',             difficulty:'Medium' },
  { id:43,  title:'LRU Cache',                                             slug:'lru-cache',                                             topic:'Linked List',             difficulty:'Medium' },
  { id:44,  title:'Merge K Sorted Lists',                                  slug:'merge-k-sorted-lists',                                  topic:'Linked List',             difficulty:'Hard'   },
  { id:45,  title:'Reverse Nodes in K-Group',                              slug:'reverse-nodes-in-k-group',                              topic:'Linked List',             difficulty:'Hard'   },
  // Trees (15)
  { id:46,  title:'Invert Binary Tree',                                    slug:'invert-binary-tree',                                    topic:'Trees',                   difficulty:'Easy'   },
  { id:47,  title:'Maximum Depth of Binary Tree',                          slug:'maximum-depth-of-binary-tree',                          topic:'Trees',                   difficulty:'Easy'   },
  { id:48,  title:'Diameter of Binary Tree',                               slug:'diameter-of-binary-tree',                               topic:'Trees',                   difficulty:'Easy'   },
  { id:49,  title:'Balanced Binary Tree',                                  slug:'balanced-binary-tree',                                  topic:'Trees',                   difficulty:'Easy'   },
  { id:50,  title:'Same Tree',                                             slug:'same-tree',                                             topic:'Trees',                   difficulty:'Easy'   },
  { id:51,  title:'Subtree of Another Tree',                               slug:'subtree-of-another-tree',                               topic:'Trees',                   difficulty:'Easy'   },
  { id:52,  title:'Lowest Common Ancestor of BST',                         slug:'lowest-common-ancestor-of-a-binary-search-tree',        topic:'Trees',                   difficulty:'Medium' },
  { id:53,  title:'Binary Tree Level Order Traversal',                     slug:'binary-tree-level-order-traversal',                     topic:'Trees',                   difficulty:'Medium' },
  { id:54,  title:'Binary Tree Right Side View',                           slug:'binary-tree-right-side-view',                           topic:'Trees',                   difficulty:'Easy'   },
  { id:55,  title:'Count Good Nodes in Binary Tree',                       slug:'count-good-nodes-in-binary-tree',                       topic:'Trees',                   difficulty:'Medium' },
  { id:56,  title:'Validate Binary Search Tree',                           slug:'validate-binary-search-tree',                           topic:'Trees',                   difficulty:'Medium' },
  { id:57,  title:'Kth Smallest Element in a BST',                         slug:'kth-smallest-element-in-a-bst',                         topic:'Trees',                   difficulty:'Medium' },
  { id:58,  title:'Construct Binary Tree from Preorder and Inorder',       slug:'construct-binary-tree-from-preorder-and-inorder-traversal', topic:'Trees',              difficulty:'Medium' },
  { id:59,  title:'Binary Tree Maximum Path Sum',                          slug:'binary-tree-maximum-path-sum',                          topic:'Trees',                   difficulty:'Hard'   },
  { id:60,  title:'Serialize and Deserialize Binary Tree',                 slug:'serialize-and-deserialize-binary-tree',                 topic:'Trees',                   difficulty:'Hard'   },
  // Heap / Priority Queue (7)
  { id:61,  title:'Kth Largest Element in a Stream',                       slug:'kth-largest-element-in-a-stream',                       topic:'Heap / Priority Queue',   difficulty:'Easy'   },
  { id:62,  title:'Last Stone Weight',                                     slug:'last-stone-weight',                                     topic:'Heap / Priority Queue',   difficulty:'Easy'   },
  { id:63,  title:'K Closest Points to Origin',                            slug:'k-closest-points-to-origin',                            topic:'Heap / Priority Queue',   difficulty:'Medium' },
  { id:64,  title:'Kth Largest Element in an Array',                       slug:'kth-largest-element-in-an-array',                       topic:'Heap / Priority Queue',   difficulty:'Medium' },
  { id:65,  title:'Task Scheduler',                                        slug:'task-scheduler',                                        topic:'Heap / Priority Queue',   difficulty:'Medium' },
  { id:66,  title:'Design Twitter',                                        slug:'design-twitter',                                        topic:'Heap / Priority Queue',   difficulty:'Medium' },
  { id:67,  title:'Find Median from Data Stream',                          slug:'find-median-from-data-stream',                          topic:'Heap / Priority Queue',   difficulty:'Hard'   },
  // Backtracking (9)
  { id:68,  title:'Subsets',                                               slug:'subsets',                                               topic:'Backtracking',            difficulty:'Medium' },
  { id:69,  title:'Combination Sum',                                       slug:'combination-sum',                                       topic:'Backtracking',            difficulty:'Medium' },
  { id:70,  title:'Permutations',                                          slug:'permutations',                                          topic:'Backtracking',            difficulty:'Medium' },
  { id:71,  title:'Subsets II',                                            slug:'subsets-ii',                                            topic:'Backtracking',            difficulty:'Medium' },
  { id:72,  title:'Combination Sum II',                                    slug:'combination-sum-ii',                                    topic:'Backtracking',            difficulty:'Medium' },
  { id:73,  title:'Word Search',                                           slug:'word-search',                                           topic:'Backtracking',            difficulty:'Medium' },
  { id:74,  title:'Palindrome Partitioning',                               slug:'palindrome-partitioning',                               topic:'Backtracking',            difficulty:'Medium' },
  { id:75,  title:'Letter Combinations of a Phone Number',                 slug:'letter-combinations-of-a-phone-number',                 topic:'Backtracking',            difficulty:'Medium' },
  { id:76,  title:'N-Queens',                                              slug:'n-queens',                                              topic:'Backtracking',            difficulty:'Hard'   },
  // Tries (3)
  { id:77,  title:'Implement Trie',                                        slug:'implement-trie-prefix-tree',                            topic:'Tries',                   difficulty:'Medium' },
  { id:78,  title:'Design Add and Search Words Data Structure',             slug:'design-add-and-search-words-data-structure',            topic:'Tries',                   difficulty:'Medium' },
  { id:79,  title:'Word Search II',                                        slug:'word-search-ii',                                        topic:'Tries',                   difficulty:'Hard'   },
  // Graphs (13)
  { id:80,  title:'Number of Islands',                                     slug:'number-of-islands',                                     topic:'Graphs',                  difficulty:'Medium' },
  { id:81,  title:'Clone Graph',                                           slug:'clone-graph',                                           topic:'Graphs',                  difficulty:'Medium' },
  { id:82,  title:'Max Area of Island',                                    slug:'max-area-of-island',                                    topic:'Graphs',                  difficulty:'Medium' },
  { id:83,  title:'Pacific Atlantic Water Flow',                            slug:'pacific-atlantic-water-flow',                           topic:'Graphs',                  difficulty:'Medium' },
  { id:84,  title:'Surrounded Regions',                                    slug:'surrounded-regions',                                    topic:'Graphs',                  difficulty:'Medium' },
  { id:85,  title:'Rotting Oranges',                                       slug:'rotting-oranges',                                       topic:'Graphs',                  difficulty:'Medium' },
  { id:86,  title:'Walls and Gates',                                       slug:'walls-and-gates',                                       topic:'Graphs',                  difficulty:'Medium' },
  { id:87,  title:'Course Schedule',                                       slug:'course-schedule',                                       topic:'Graphs',                  difficulty:'Medium' },
  { id:88,  title:'Course Schedule II',                                    slug:'course-schedule-ii',                                    topic:'Graphs',                  difficulty:'Medium' },
  { id:89,  title:'Redundant Connection',                                  slug:'redundant-connection',                                  topic:'Graphs',                  difficulty:'Medium' },
  { id:90,  title:'Number of Connected Components in an Undirected Graph', slug:'number-of-connected-components-in-an-undirected-graph', topic:'Graphs',                  difficulty:'Medium' },
  { id:91,  title:'Graph Valid Tree',                                      slug:'graph-valid-tree',                                      topic:'Graphs',                  difficulty:'Medium' },
  { id:92,  title:'Word Ladder',                                           slug:'word-ladder',                                           topic:'Graphs',                  difficulty:'Hard'   },
  // Advanced Graphs (6)
  { id:93,  title:'Reconstruct Itinerary',                                 slug:'reconstruct-itinerary',                                 topic:'Advanced Graphs',         difficulty:'Hard'   },
  { id:94,  title:'Min Cost to Connect All Points',                        slug:'min-cost-to-connect-all-points',                        topic:'Advanced Graphs',         difficulty:'Medium' },
  { id:95,  title:'Network Delay Time',                                    slug:'network-delay-time',                                    topic:'Advanced Graphs',         difficulty:'Medium' },
  { id:96,  title:'Swim in Rising Water',                                  slug:'swim-in-rising-water',                                  topic:'Advanced Graphs',         difficulty:'Hard'   },
  { id:97,  title:'Alien Dictionary',                                      slug:'alien-dictionary',                                      topic:'Advanced Graphs',         difficulty:'Hard'   },
  { id:98,  title:'Cheapest Flights Within K Stops',                       slug:'cheapest-flights-within-k-stops',                       topic:'Advanced Graphs',         difficulty:'Medium' },
  // 1D Dynamic Programming (12)
  { id:99,  title:'Climbing Stairs',                                       slug:'climbing-stairs',                                       topic:'1D Dynamic Programming',  difficulty:'Easy'   },
  { id:100, title:'Min Cost Climbing Stairs',                              slug:'min-cost-climbing-stairs',                              topic:'1D Dynamic Programming',  difficulty:'Easy'   },
  { id:101, title:'House Robber',                                          slug:'house-robber',                                          topic:'1D Dynamic Programming',  difficulty:'Medium' },
  { id:102, title:'House Robber II',                                       slug:'house-robber-ii',                                       topic:'1D Dynamic Programming',  difficulty:'Medium' },
  { id:103, title:'Longest Palindromic Substring',                         slug:'longest-palindromic-substring',                         topic:'1D Dynamic Programming',  difficulty:'Medium' },
  { id:104, title:'Palindromic Substrings',                                slug:'palindromic-substrings',                                topic:'1D Dynamic Programming',  difficulty:'Medium' },
  { id:105, title:'Decode Ways',                                           slug:'decode-ways',                                           topic:'1D Dynamic Programming',  difficulty:'Medium' },
  { id:106, title:'Coin Change',                                           slug:'coin-change',                                           topic:'1D Dynamic Programming',  difficulty:'Medium' },
  { id:107, title:'Maximum Product Subarray',                              slug:'maximum-product-subarray',                              topic:'1D Dynamic Programming',  difficulty:'Medium' },
  { id:108, title:'Word Break',                                            slug:'word-break',                                            topic:'1D Dynamic Programming',  difficulty:'Medium' },
  { id:109, title:'Longest Increasing Subsequence',                        slug:'longest-increasing-subsequence',                        topic:'1D Dynamic Programming',  difficulty:'Medium' },
  { id:110, title:'Partition Equal Subset Sum',                            slug:'partition-equal-subset-sum',                            topic:'1D Dynamic Programming',  difficulty:'Medium' },
  // 2D Dynamic Programming (11)
  { id:111, title:'Unique Paths',                                          slug:'unique-paths',                                          topic:'2D Dynamic Programming',  difficulty:'Medium' },
  { id:112, title:'Longest Common Subsequence',                            slug:'longest-common-subsequence',                            topic:'2D Dynamic Programming',  difficulty:'Medium' },
  { id:113, title:'Best Time to Buy and Sell Stock with Cooldown',         slug:'best-time-to-buy-and-sell-stock-with-cooldown',         topic:'2D Dynamic Programming',  difficulty:'Medium' },
  { id:114, title:'Coin Change II',                                        slug:'coin-change-ii',                                        topic:'2D Dynamic Programming',  difficulty:'Medium' },
  { id:115, title:'Target Sum',                                            slug:'target-sum',                                            topic:'2D Dynamic Programming',  difficulty:'Medium' },
  { id:116, title:'Interleaving String',                                   slug:'interleaving-string',                                   topic:'2D Dynamic Programming',  difficulty:'Medium' },
  { id:117, title:'Longest Increasing Path in a Matrix',                   slug:'longest-increasing-path-in-a-matrix',                   topic:'2D Dynamic Programming',  difficulty:'Hard'   },
  { id:118, title:'Distinct Subsequences',                                 slug:'distinct-subsequences',                                 topic:'2D Dynamic Programming',  difficulty:'Hard'   },
  { id:119, title:'Edit Distance',                                         slug:'edit-distance',                                         topic:'2D Dynamic Programming',  difficulty:'Hard'   },
  { id:120, title:'Burst Balloons',                                        slug:'burst-balloons',                                        topic:'2D Dynamic Programming',  difficulty:'Hard'   },
  { id:121, title:'Regular Expression Matching',                           slug:'regular-expression-matching',                           topic:'2D Dynamic Programming',  difficulty:'Hard'   },
  // Greedy (8)
  { id:122, title:'Maximum Subarray',                                      slug:'maximum-subarray',                                      topic:'Greedy',                  difficulty:'Medium' },
  { id:123, title:'Jump Game',                                             slug:'jump-game',                                             topic:'Greedy',                  difficulty:'Medium' },
  { id:124, title:'Jump Game II',                                          slug:'jump-game-ii',                                          topic:'Greedy',                  difficulty:'Medium' },
  { id:125, title:'Gas Station',                                           slug:'gas-station',                                           topic:'Greedy',                  difficulty:'Medium' },
  { id:126, title:'Hand of Straights',                                     slug:'hand-of-straights',                                     topic:'Greedy',                  difficulty:'Medium' },
  { id:127, title:'Merge Triplets to Form Target Triplet',                 slug:'merge-triplets-to-form-target-triplet',                 topic:'Greedy',                  difficulty:'Medium' },
  { id:128, title:'Partition Labels',                                      slug:'partition-labels',                                      topic:'Greedy',                  difficulty:'Medium' },
  { id:129, title:'Valid Parenthesis String',                              slug:'valid-parenthesis-string',                              topic:'Greedy',                  difficulty:'Medium' },
  // Intervals (6)
  { id:130, title:'Insert Interval',                                       slug:'insert-interval',                                       topic:'Intervals',               difficulty:'Medium' },
  { id:131, title:'Merge Intervals',                                       slug:'merge-intervals',                                       topic:'Intervals',               difficulty:'Medium' },
  { id:132, title:'Non Overlapping Intervals',                             slug:'non-overlapping-intervals',                             topic:'Intervals',               difficulty:'Medium' },
  { id:133, title:'Meeting Rooms',                                         slug:'meeting-rooms',                                         topic:'Intervals',               difficulty:'Easy'   },
  { id:134, title:'Meeting Rooms II',                                      slug:'meeting-rooms-ii',                                      topic:'Intervals',               difficulty:'Medium' },
  { id:135, title:'Minimum Interval to Include Each Query',                slug:'minimum-interval-to-include-each-query',                topic:'Intervals',               difficulty:'Hard'   },
  // Math & Geometry (8)
  { id:136, title:'Rotate Image',                                          slug:'rotate-image',                                          topic:'Math & Geometry',         difficulty:'Medium' },
  { id:137, title:'Spiral Matrix',                                         slug:'spiral-matrix',                                         topic:'Math & Geometry',         difficulty:'Medium' },
  { id:138, title:'Set Matrix Zeroes',                                     slug:'set-matrix-zeroes',                                     topic:'Math & Geometry',         difficulty:'Medium' },
  { id:139, title:'Happy Number',                                          slug:'happy-number',                                          topic:'Math & Geometry',         difficulty:'Easy'   },
  { id:140, title:'Plus One',                                              slug:'plus-one',                                              topic:'Math & Geometry',         difficulty:'Easy'   },
  { id:141, title:'Pow(x, n)',                                             slug:'powx-n',                                                topic:'Math & Geometry',         difficulty:'Medium' },
  { id:142, title:'Multiply Strings',                                      slug:'multiply-strings',                                      topic:'Math & Geometry',         difficulty:'Medium' },
  { id:143, title:'Detect Squares',                                        slug:'detect-squares',                                        topic:'Math & Geometry',         difficulty:'Medium' },
  // Bit Manipulation (7)
  { id:144, title:'Single Number',                                         slug:'single-number',                                         topic:'Bit Manipulation',        difficulty:'Easy'   },
  { id:145, title:'Number of 1 Bits',                                      slug:'number-of-1-bits',                                      topic:'Bit Manipulation',        difficulty:'Easy'   },
  { id:146, title:'Counting Bits',                                         slug:'counting-bits',                                         topic:'Bit Manipulation',        difficulty:'Easy'   },
  { id:147, title:'Reverse Bits',                                          slug:'reverse-bits',                                          topic:'Bit Manipulation',        difficulty:'Easy'   },
  { id:148, title:'Missing Number',                                        slug:'missing-number',                                        topic:'Bit Manipulation',        difficulty:'Easy'   },
  { id:149, title:'Sum of Two Integers',                                   slug:'sum-of-two-integers',                                   topic:'Bit Manipulation',        difficulty:'Medium' },
  { id:150, title:'Reverse Integer',                                       slug:'reverse-integer',                                       topic:'Bit Manipulation',        difficulty:'Medium' },
]
